service: phaser-mmo-server
# app and org for use with dashboard.serverless.com
app: phaser-mmo-server
org: eduardofidera

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes

functions:
  websocket:
    handler: src/websocketHandler.handler
    events:
      - websocket:
          # Handles new connection requests
          route: $connect

      - websocket:
          # Handles all unrouted messages
          route: $default

      - websocket:
          # Handles disconnect messages
          route: $disconnect

plugins:
  - serverless-plugin-typescript
  - serverless-offline
